apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-app-config
    app.kubernetes.io/name:  {{ .Release.Name }}-app-config
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-app-config
  namespace: {{ .Release.Namespace }}
data:
  APP_NAME: "{{ .Release.Name }}"
  APP_NAMESPACE: "{{ .Release.Namespace }}"
