apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }} 
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: {{ .Values.application.appPort }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }} 
    weight: 100
  wildcardPolicy: None
