apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-model-config
  namespace: {{ .Release.Namespace }}
data:
  MODEL_ENDPOINT: "http://{{ .Release.Name }}-model-server:{{ .Values.model.modelServicePort }}"