apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-model-config
  namespace: {{ .Values.namespace }}
data:
  MODEL_ENDPOINT: "http://{{ .Values.name }}-model-server:{{ .Values.modelServicePort }}"
  {%- if .Values.modelServiceType == "vllm" %}
  MODEL_NAME: "{{ .Values.modelName }}"
  {%- endif %}