apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}-model-config
data:
  GITHUB_ORG_NAME: "{{ .Values.gitops.githubOrgName }}"
  GITHUB_APP_REPO: "{{ .Values.gitops.githubOrgName }}/{{ .Values.application.name }}"
  GITHUB_GITOPS_REPO: "{{ .Values.gitops.githubOrgName }}/{{ .Values.application.name }}-gitops"
  GITHUB_SOURCE_REPO: "{{ .Values.gitops.gitSourceRepo }}"
  GITHUB_DEFAULT_BRANCH: "{{ .Values.gitops.gitDefaultBranch }}"