apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: {{ .Values.application.name }}-tekton-repository
spec:
  url: "https://github.com/{{ .Values.gitops.githubOrgName }}/{{ .Values.application.name }}.git"
