name: Verify updated gitops resources

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-updated-gitops-resources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Run generate.sh and check if the ai-lab-app based charts are up-to-date
        run: |
          bash generate.sh
          if [[ ! -z $(git status -s) ]]
          then
            echo 'The script `./generate.sh` did introduce changes, which should ideally be checked in as part of the PR.'
            git status
            exit 1
          fi
