apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-app-config
    app.kubernetes.io/name:  {{ .Release.Name }}-app-config
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-app-config
  namespace: {{ .Release.Namespace }}
data:
  APP_NAME: "{{ .Release.Name }}"
  APP_NAMESPACE: "{{ .Release.Namespace }}"
  APP_DIR_NAME: "chatbot"
  APP_EXEC_NAME: "chatbot_ui.py"
  GITHUB_ORG_NAME: "{{ .Values.gitops.githubOrgName }}"  
  GITHUB_SOURCE_REPO: "{{ .Values.gitops.gitSourceRepo }}"
  GITHUB_TETKON_SOURCE_REPO: "redhat-ai-dev/ai-lab-helm-charts"
  GITHUB_DEFAULT_BRANCH: "{{ .Values.gitops.gitDefaultBranch }}"
  QUAY_ACCOUNT_NAME: "{{ .Values.gitops.quayAccountName }}"
  GH_VERSION: "2.62.0"