apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}-model-server
    app.kubernetes.io/name: {{ .Release.Name }}-model-server
  name: {{ .Release.Name }}-model-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.model.modelServicePort }}
    protocol: TCP
    targetPort: {{ .Values.model.modelServicePort }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}-model-server
