apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-model-config
data:
  {{ if .Values.model.existingModelServer }}
  MODEL_ENDPOINT: "{{ .Values.model.modelEndpoint }}"
  {{ else }}
  MODEL_ENDPOINT: "http://{{ .Release.Name }}-model-server:{{ .Values.model.modelServicePort }}"
  {{ end }}
  {{- if or .Values.model.vllmSelected .Values.model.existingModelServer }}
  MODEL_NAME: "{{ .Values.model.modelName }}"
  {{ end }}