apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }} 
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.application.appPort }}
    protocol: TCP
    targetPort: {{ .Values.application.appPort }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }} 
