apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: {{ .Release.Name }}-tekton-repository
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name:  {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}  
spec:
  url: "https://github.com/{{ .Values.gitops.githubOrgName }}/{{ .Release.Name }}"


